-- 1. FREEPDB1 열기
ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN;

-- 2. FREEPDB1로 전환
ALTER SESSION SET CONTAINER = FREEPDB1;

-- 3. USERS 테이블스페이스가 없으면 생성
CREATE TABLESPACE users
DATAFILE 'C:/app/ASUS/product/23ai/oradata/FREE/FREEPDB1/users01.dbf'
SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- 4. SCOTT 계정 생성
CREATE USER scott IDENTIFIED BY welcome1
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;

-- 5. 권한 부여
GRANT CONNECT, RESOURCE TO scott;